defaults:
  env: &env
    docker:
      - image: circleci/node:8-browsers
  install: &install
    - checkout
    - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
    - restore_cache:
        key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
    - run: yarn install --frozen-lockfile
    - save_cache:
        key: yarn-dependency-cache-{{ checksum "yarn.lock" }}
        paths:
          - node_modules
  run_tests: &run_tests
    - run: make test
    - store_test_results:
        path: junit-reports
  run_coverage: &run_coverage
    - run: yarn run karma start karma.conf.coverage.js
    - store_test_results:
        path: junit-reports
    - run: yarn run codecov
version: 2
jobs:
  test:
    <<: *env
    steps:
      - *install
      - *run_tests
  coverage:
    <<: *env
    steps:
      - *install
      - *run_coverage
  publish:
    <<: *env
    steps:
      - checkout
      - attach_workspace: { at: . }
      - run: npm publish .
workflows:
  version: 2
  test_and_publish:
    jobs:
      - test: &defaultPublish
          filters:
            tags:
              only: /.*/
      - coverage: *defaultPublish
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
